#!/bin/bash
pid=$$

# remove the # from next line to background learner
#(
{
    echo "$(date) ${pid}-start ($*) /tmp/sendmail-msg-$$.txt"
    # set -x
    # id -a
    # env
    cat > /tmp/sendmail-msg-${pid}.txt
    /usr/bin/sa-learn "$@" /tmp/sendmail-msg-${pid}.txt
    echo "$(date) $$-end rc=$?"
} >/tmp/antispam.${pid}.log 2>&1

cat /tmp/antispam.${pid}.log >>/tmp/sa-learn-pipe.log
rm -f /tmp/antispam.${pid}.log /tmp/sendmail-msg-${pid}.txt
true

#remove the # from next line to background learner
#) &

exit 0
